import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#eff1f3",
        "on-secondary-container": "#217128",
        "tertiary-container": "#6d4500",
        "on-primary-fixed-variant": "#0e4688",
        "on-primary-fixed": "#001b3e",
        "on-error": "#ffffff",
        "secondary-container": "#a0f399",
        "primary": "#00366f",
        "on-secondary": "#ffffff",
        "outline": "#737782",
        "on-background": "#191c1e",
        "tertiary-fixed-dim": "#ffb957",
        "surface-container-high": "#e6e8ea",
        "on-secondary-fixed-variant": "#005312",
        "surface-container": "#eceef0",
        "surface-variant": "#e0e3e5",
        "surface-dim": "#d8dadc",
        "surface-container-low": "#f2f4f6",
        "surface-tint": "#305ea1",
        "error-container": "#ffdad6",
        "surface-bright": "#f8f9fb",
        "surface": "#f8f9fb",
        "outline-variant": "#c3c6d2",
        "surface-container-highest": "#e0e3e5",
        "primary-container": "#1a4d8f",
        "on-secondary-fixed": "#002204",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffddb5",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#643f00",
        "secondary": "#1b6d24",
        "on-primary-container": "#9dc0ff",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1e",
        "background": "#f8f9fb",
        "secondary-fixed-dim": "#88d982",
        "secondary-fixed": "#a3f69c",
        "on-tertiary-fixed": "#2a1800",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#434750",
        "primary-fixed": "#d6e3ff",
        "on-tertiary-container": "#ffae31",
        "primary-fixed-dim": "#a9c7ff",
        "tertiary": "#4e3000",
        "inverse-surface": "#2d3133",
        "on-error-container": "#93000a",
        "inverse-primary": "#a9c7ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        base: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "sidebar-width": "260px",
      },
      fontFamily: {
        "sans": ["IBM Plex Sans", "sans-serif"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "headline-md": ["IBM Plex Sans", "sans-serif"],
        "label-sm": ["IBM Plex Sans", "sans-serif"],
        "label-lg": ["IBM Plex Sans", "sans-serif"],
        "display": ["IBM Plex Sans", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "headline-lg-mobile": ["IBM Plex Sans", "sans-serif"],
        "headline-lg": ["IBM Plex Sans", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
